### ISSUE TITLE
Write permissions on WPEngine

### ISSUE THREAD

**Issue by hellomrdavis** [dcooney/ajax-load-more#47]
Getting multiple write errors in my error log on WPEngine. I've reset file permissions and contacted their support about it. Setting the permissions to 777 isn't allowed on their system. The settings in Wordpress though has the green light for write permissions but still getting the errors. Here are the error messages:

[Fri Nov 14 14:58:22 2014] [error] [client XXX] PHP Warning: fopen(/nas/wp/www/cluster-2759/DOMAIN/wp-content/plugins/ajax-load-more/core/repeater/default.php) [<a href='function.fopen'>function.fopen</a>]: failed to open stream: Permission denied in /nas/wp/www/cluster-2759/DOMAIN/wp-content/plugins/ajax-load-more/admin/admin.php on line 77, referer: http://www.DOMAIN.com/news/
[Fri Nov 14 14:58:22 2014] [error] [client XXX] PHP Warning: fwrite() expects parameter 1 to be resource, boolean given in /nas/wp/www/cluster-2759/DOMAIN/wp-content/plugins/ajax-load-more/admin/admin.php on line 78, referer: http://www.DOMAIN.com/news/
[Fri Nov 14 14:58:22 2014] [error] [client XXX] PHP Warning: fread() expects parameter 1 to be resource, boolean given in /nas/wp/www/cluster-2759/DOMAIN/wp-content/plugins/ajax-load-more/admin/admin.php on line 79, referer: http://www.DOMAIN.com/news/
[Fri Nov 14 14:58:22 2014] [error] [client XXX] PHP Warning: fclose() expects parameter 1 to be resource, boolean given in /nas/wp/www/cluster-2759/DOMAIN/wp-content/plugins/ajax-load-more/admin/admin.php on line 80, referer: http://www.DOMAIN.com/news/

Anybody else run into this issue before and know of a workaround?

**Comment by jamblo** [comment]
Hi there

I have a site on WP Engine that gets a lot of traffic and we've been experiencing 502 errors. This is WP Engines response:

Looks like there's an error coming from some pages - it's a PHP Warning which could be playing into it.
PHP Warning: fclose() expects parameter 1 to be resource, boolean given in /nas/wp/www/cluster-2107/username/wp-content/plugins/ajax-load-more/admin/admin.php on line 81, referer: http://www.username.com/hype/ 

Are hellomrdavis and my issue related? I really need to get to the bottom of this one!

Thanks in advance.
James
